function ButterDogReset() {
    document.write('<body style="background-color:rgb(231, 213, 45);">  </body>    <p style="font-size: large; color:rgb(255, 255, 255); position:absolute; font-family:Arial, Helvetica, sans-serif; left: 80px; top: 1.5% ;">The Code To Redeem is (butterdog20222001)</p>');
        }

        function ButterPlatformerReset() {
            document.write('<body style="background-color:rgb(231, 213, 45);">  </body>    <p style="font-size: large; color:rgb(255, 255, 255); position:absolute; font-family:Arial, Helvetica, sans-serif; left: 80px; top: 1.5% ;">The Code To Redeem is (butterdog2021152001)</p>');
                }

                function ButterPingPongReset() {
                    document.write('<body style="background-color:rgb(231, 213, 45);">  </body>    <p style="font-size: large; color:rgb(255, 255, 255); position:absolute; font-family:Arial, Helvetica, sans-serif; left: 80px; top: 1.5% ;">The Code To Redeem is (pingpongbutterdoghitsdawn523)</p>');
                        }